add codeartifact setup [WIP]
iheartradio/pipeline pull request #91
Opened 2021-02-22 22:02 UTC by Christian-Paul

2021-02-23 19:51 UTC, adityaghosh approved these changes

2021-02-23 19:58 UTC, jnguyengit approved these changes

2021-02-23 21:31 UTC, lbedner requested changes
@Christian-Paul why would we need to rename from `pipeline` -> `pipeine-ihr`? If we only host on our own private package index, what type of conflicts are there? 🤔

2021-02-23 21:58 UTC, Christian-Paul commented
@lbedner It's not a hard requirement to rename it. But if we don't, doing a `pip install pipeline` would get us a completely different library from PyPi. 

Trying to install a list of mixed packages (from both public and private index) with `pip install --extra-index-url requirements.txt` is unpredictable in how it resolves and decides which index to use if `pipeline` is available in both indexes.

So what we can/should do is install our private libraries in one step with `pip install --index-url private-requirements.txt` and our public libraries in another step with the regular `pip install public-requirements.txt`

We should do that final step regardless of if we rename the library or not, but renaming it just makes it easier to avoid accidentally getting the random PyPi `pipeline` when developing or changing our processes in the future.

2021-02-23 22:04 UTC, lbedner commented
> @lbedner It's not a hard requirement to rename it. But if we don't, doing a `pip install pipeline` would get us a completely different library from PyPi.
> 
> Trying to install a list of mixed packages (from both public and private index) with `pip install --extra-index-url requirements.txt` is unpredictable in how it resolves and decides which index to use if `pipeline` is available in both indexes.
> 
> So what we can/should do is install our private libraries in one step with `pip install --index-url private-requirements.txt` and our public libraries in another step with the regular `pip install public-requirements.txt`
> 
> We should do that final step regardless of if we rename the library or not, but renaming it just makes it easier to avoid accidentally getting the random PyPi `pipeline` when developing or changing our processes in the future.

@Christian-Paul okay, that's fair.

2021-02-23 22:04 UTC, lbedner approved these changes

2021-02-24 21:06 UTC, e-agbanyo approved these changes

2021-02-24 21:06 UTC, e-agbanyo commented on .travis.yml
> +#  - name: deploy
Do we need this and the following line? I see that it is commented out.

2021-02-24 21:12 UTC, merged